### PR TITLE
Add `manager` plugin

### PR DESCRIPTION
**Pull request by taconi**
This is a

* [x] New plugin.
* [ ] Update to an existing plugin.

Plugin name and version: manager 3.3.0

Plugin source code zip file: https://codeberg.org/micro-plugins/manager/archive/v3.3.0.zip.

Checklist:

* [x] Plugin has a repo.json listing the `Name`, `Description`, `Website`, and `License`.
* [x] I have read the instructions at https://github.com/micro-editor/plugin-channel#adding-your-own-plugin.

---

The plugin manager provides a way to manage linters, formatters, commands, keybindings, settings, plugins.

Below is an example of use, for more details see the [documentation](https://manager.readthedocs.io/) or open an [issue](https://codeberg.org/micro-plugins/manager/issues) for questions, suggestions or bug reports.
## Dashboard

Inspired by [telescope.nvim], [project.nvim], [alpha-nvim] and the lunarvim dashboard
we have a dash to manage your projects and files.

Open the dashboard with the command `> manager dash` or with the default bind `Alt-Ctrl-o`.

dashboard

For more details see the [dashboard documentation].

## Info Buffer

A buffer with the configuration status can be viewed with the `manager info` command
or with the default bind `Alt-Ctrl-q`.

infopane

Use arrows to navigate statuses.

## An example `~/.config/micro/init.lua`

```lua title="~/.config/micro/init.lua"
linters = {  -- (1)!
  {
    cmd = 'tsc --noEmit --pretty false %f',
    errorformat = '%f%(%l,%c%): %m',
    filetypes = { 'typescript' },
  },
}

formatters = {  -- (2)!
  {
    cmd = 'isort -l 79 --trailing-comma --multi-line 3 %f',
    name = 'isort',  -- command name: `> isort`
    bind = 'Alt-g',
    onSave = true,
    filetypes = { 'python' },
  },
}

bindings = {  -- (3)!
  { key = 'Alt-m', cmd = 'JumpToMatchingBrace', overwrite = true },
}

settings = {  -- (4)!
  ['ft:json'] = { commenttype = '// %s' },
  colorscheme = 'one-dark',
  pluginrepos = { 'https://codeberg.org/micro-plugins/manager/raw/branch/main/repo.json' },
  tabstospaces = true,
}

plugins = {  -- (5)!
  {
    'lsp',
    git = { url = 'https://github.com/AndCake/micro-plugin-lsp.git', branch = 'main' },
    config = {
      ['lsp.formatOnSave'] = false,
    },
    bindings = {
      { key = 'CtrlSpace', cmd = 'command:lspcompletion', overwrite = true },
    },
  },
}

commands = {  -- (6)!
  {
    -- Open a new Vsplit (on the very left)
    name = { 'vsp',  'vsplitleft' },
    action = function(bp)
      local micro = import('micro')
      local buffer = import('micro/buffer')

      bp:VSplitIndex(buffer.NewBuffer('', ''), false) -- right=false
      micro.InfoBar():Message('New open file')
    end,
    bindings = {
      { key = 'Alt-|', cmd = 'command:vsp', overwrite = true },
    },
    complete = config.NoComplete,
  },
}
```

1. For more details see the linters [documentation](https://manager.readthedocs.io/linters/).
2. For more details see the formatter [documentation](https://manager.readthedocs.io/formatters).
3. For more details see the binding [documentation](https://manager.readthedocs.io/bindings).
4. For more details see the settings [documentation](https://manager.readthedocs.io/settings).
5. For more details see the plugin [documentation](https://manager.readthedocs.io/plugins).
6. For more details see the command [documentation](https://manager.readthedocs.io/commands).

[dashboard documentation]: https://manager.readthedocs.io/dashboard
[telescope.nvim]: https://github.com/nvim-telescope/telescope.nvim
[project.nvim]: https://github.com/ahmedkhalf/project.nvim
[alpha-nvim]: https://github.com/goolord/alpha-nvim

### CODE REVIEW

**Comment by taconi** [comment]
Hey 👋
Is there anything missing for this PR to be merged?

**Comment by taconi** [comment]
@dmaluka @JoeKar @dustdfg @Andriamanitra @zyedidia Could anyone review?

**Review by JoeKar — APPROVED** [review]
I see no reason to prevent it from being added into the official plugin-channel.

**Comment by taconi** [comment]
PR abandoned because I got tired of begging. The plugin will no longer be maintained, if anyone wants to maintain it, let me know and I will transfer the repository

**Pull request closed without merging**
