### PR TITLE
alphabetize repo list, add fish plugin

### PR DESCRIPTION
**Pull request by onodera-punpun**

### CODE REVIEW

**Comment by zyedidia** [comment]
The Version section in your `repo.json` should be `0.1.0` instead of `0.1`. Otherwise it looks good.

**Comment by onodera-punpun** [comment]
So versions should always be like X.X.X?

**Comment by zyedidia** [comment]
Yup. That's the semver way.

**Comment by onodera-punpun** [comment]
Should be fixed now :)

**Comment by zyedidia** [comment]
Oops it seems there's actually a bit more to fix. The url should link to a zip file not a tarball. Use `"Url": "https://github.com/onodera-punpun/micro-fish-plugin/archive/0.1.zip"` instead.

If you want to test the installation yourself, you can add `https://raw.githubusercontent.com/onodera-punpun/micro-fish-plugin/master/repo.json` as a repo by adding the following to you settings.json file:

```json
"pluginrepos": [
    "https://raw.githubusercontent.com/onodera-punpun/micro-fish-plugin/master/repo.json"
]
```

I plan to document all this stuff soon.

**Comment by onodera-punpun** [comment]
Yup, fixed

**Pull request merged**
